app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| 基础权限
|--------------------------------------------------------------------------
*/
RouteGroup::make('auth')->before('guest')->controller('AuthorityController')->go(function ($route) {

    # 退出
    $route->get('logout')->as('logout')->uses('getLogout')->beforeClear();

    # 登录
    $route->get( 'signin'                   )->as('signin'        )->uses('getSignin'         );
    $route->post('signin'                   )                      ->uses('postSignin'        );
    # 注册
    $route->get( 'signup'                   )->as('signup'        )->uses('getSignup'         );
    $route->post('signup'                   )                      ->uses('postSignup'        );
    # 注册成功提示用户激活
    $route->get( 'success/{email}'          )->as('signupSuccess' )->uses('getSignupSuccess'  );
    # 激活账号
    $route->get( 'activate/{activationCode}')->as('activate'      )->uses('getActivate'       );
    # 忘记密码
    $route->get( 'forgot-password'          )->as('forgotPassword')->uses('getForgotPassword' );
    $route->post('forgot-password'          )                      ->uses('postForgotPassword');
    # 密码重置
    $route->get( 'forgot-password/{token}'  )->as('reset'         )->uses('getReset'          );
    $route->post('forgot-password/{token}'  )                      ->uses('postReset'         );

});

/*
|--------------------------------------------------------------------------
| 管理员后台
|--------------------------------------------------------------------------
*/
Route::group(array('prefix' => 'admin', 'before' => 'auth|admin'), function () {

    # 后台首页
    RouteGroup::make()->controller('AdminController')->go(function ($route) {
        $route->get('/')->as('admin')->uses('getIndex');
    });

    # 用户管理
    RouteGroup::make('users')->as('users')->controller('Admin_UserResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )->before('not.self')
              ->update()->before('not.self');
        $route->delete('{id}')->as('destroy')->uses('destroy')->before('not.self');
    });

    # 文章分类管理
    RouteGroup::make('categories')->as('categories')->controller('Admin_CategoryResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

    # 文章管理
    RouteGroup::make('articles')->as('articles')->controller('Admin_ArticleResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

});


/*
|--------------------------------------------------------------------------
| 用户中心
|--------------------------------------------------------------------------
*/
RouteGroup::make('account')->as('account')->before('auth')->controller('AccountController')->go(function ($route) {

    # 用户中心首页
    $route->get(   '/'               )->as('index'             )->uses('getIndex'         );
    # 修改当前账号密码
    $route->get(   'change-password' )->as('changePassword'    )->uses('getChangePassword');
    $route->put(   'change-password' )                          ->uses('putChangePassword');
    # 更改头像
    $route->get(   'change-portrait' )->as('changePortrait'    )->uses('getChangePortrait');
    $route->put(   'change-portrait' )                          ->uses('putChangePortrait');
    # 我的评论管理
    $route->get(   'my-comments'     )->as('myComments'        )->uses('getMyComments'    );
    $route->delete('my-comments/{id}')->as('myComments.destroy')->uses('deleteMyComment'  );

});

/*
|--------------------------------------------------------------------------
| 博客
|--------------------------------------------------------------------------
*/
RouteGroup::make()->controller('BlogController')->go(function ($route) {

    # 博客首页
    $route->get( '/'            )->as('home'            )->uses('getIndex'           );
    # 分类文章列表
    $route->get( 'category/{id}')->as('categoryArticles')->uses('getCategoryArticles');
    # 展示博客文章
    $route->get( '{slug}'       )->as('blog.show'       )->uses('getBlogShow'        );
    # 提交文章评论
    $route->post('{slug}'       )                        ->uses('postBlogComment'    )->before('auth');

})/*->ddAll()*/;

/*
|--------------------------------------------------------------------------
| 特殊功能
|--------------------------------------------------------------------------
*/

app/models/Article.php
<?php

use \Michelf\MarkdownExtra;

/**
 * 文章
 */
class Article extends BaseModel
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = true;

/*
|--------------------------------------------------------------------------
| 模型对象关系
|--------------------------------------------------------------------------
*/
    /**
     * 文章的分类
     * 一对多逆向
     * @return object Category
     */
    public function category()
    {
        return $this->belongsTo('Category', 'category_id');
    }

    /**
     * 文章的作者
     * 一对多逆向
     * @return object User
     */
    public function user()
    {
        return $this->belongsTo('User', 'user_id');
    }

    /**
     * 文章的评论
     * 一对多
     * @return object Illuminate\Database\Eloquent\Collection
     */
    public function comments()
    {
        return $this->hasMany('Comment', 'article_id');
    }

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 文章内容（原始）
     * @return string
     */
    public function getContentAttribute($value)
    {
        return strip($value);
    }

    /**
     * 文章内容（HTML 格式）
     * @return string
     */
    public function getContentHtmlAttribute()
    {
        switch ($this->content_format) {
            case 'markdown':
                return MarkdownExtra::defaultTransform($this->content);
            case 'html':
                return $this->content;
        }
    }

    /**
     * 文章内容（Markdown 格式）
     * @return string
     */
    public function getContentMarkdownAttribute()
    {
        switch ($this->content_format) {
            case 'markdown':
                return $this->content;
            case 'html':
                return new HTML_To_Markdown($this->content);
        }
    }


}

app/models/BaseModel.php
<?php

class BaseModel extends Eloquent
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = false;

    /**
     * 自动维护时间戳
     * @var boolean
     */
    public $timestamps = true;

    /**
     * 其它需要使用日期调整器的字段
     * @var array
     */
    protected $dates = array();

    /**
     * 集体赋值白名单（高优先级）
     * @var array
     */
    protected $fillable = array();

    /**
     * 集体赋值黑名单
     * @var array
     */
    protected $guarded = array();

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 友好的创建时间
     * @return string
     */
    public function getFriendlyCreatedAtAttribute()
    {
        return friendly_date($this->created_at);
    }

    /**
     * 友好的更新时间
     * @return string
     */
    public function getFriendlyUpdatedAtAttribute()
    {
        return friendly_date($this->updated_at);
    }

    /**
     * 友好的删除时间
     * @return string
     */
    public function getFriendlyDeletedAtAttribute()
    {
        return friendly_date($this->deleted_at);
    }


}

app/views/admin/article/create.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent 添加新{{ $resourceName }} @stop

@section('beforeStyle')
    @parent
    {{ style('bootstrap-markdown') }}
@stop

@section('style')
.nav-tabs>li.active>a
{
    background-color: #f8f8f8 !important;
}
@parent @stop

@section('container')

    @include('w.notification')
    <h3>
        添加新{{ $resourceName }}
        <div class="pull-right">
            <a href="{{ route($resource.'.index') }}" class="btn btn-sm btn-default">
                &laquo; 返回{{ $resourceName }}列表
            </a>
        </div>
    </h3>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-general" data-toggle="tab">主要内容</a></li>
        <li><a href="#tab-meta-data" data-toggle="tab">SEO</a></li>
    </ul>

    <form class="form-horizontal" method="post" action="{{ route($resource.'.store') }}" autocomplete="off"
        style="background:#f8f8f8;padding:1em;border:1px solid #ddd;border-top:0;">
        <!-- CSRF Token -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />

        <!-- Tabs Content -->
        <div class="tab-content">

            <!-- General tab -->
            <div class="tab-pane active" id="tab-general" style="margin:0 1em;">

                <div class="form-group">
                    <label for="category">分类</label>
                    {{ $errors->first('category', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    {{ Form::select('category', $categoryLists, 1, array('class' => 'form-control')) }}
                </div>

                <div class="form-group">
                    <label for="title">标题</label>
                    {{ $errors->first('title', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="text" name="title" id="title" value="{{ Input::old('title') }}" />
                </div>

                <div class="form-group">
                    <label for="slug">Slug</label>
                    {{ $errors->first('slug', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <div class="input-group">
                        <span class="input-group-addon" >
                            {{ str_finish(URL::to('/'), '/') }}
                        </span>
                        <input class="form-control" type="text" name="slug" id="slug" value="{{ Input::old('slug') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="content">内容</label>
                    {{ $errors->first('content', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <textarea id="content" class="form-control" data-provide="markdown"
                        name="content" rows="10">{{ Input::old('content') }}</textarea>
                </div>

            </div>

            <!-- Meta Data tab -->
            <div class="tab-pane" id="tab-meta-data" style="margin:0 1em;">

                <div class="form-group">
                    <label for="meta_title">Meta Title</label>
                    <input class="form-control" type="text" name="meta_title" id="meta_title" value="{{ Input::old('meta_title') }}" />
                </div>

                <div class="form-group">
                    <label for="meta_description">Meta Description</label>
                    <input class="form-control" type="text" name="meta_description" id="meta_description" value="{{ Input::old('meta_description') }}" />
                </div>

                <div class="form-group">
                    <label for="meta_keywords">Meta Keywords</label>
                    <input class="form-control" type="text" name="meta_keywords" id="meta_keywords" value="{{ Input::old('meta_keywords') }}" />
                </div>

            </div>

        </div>

        <!-- Form actions -->
        <div class="control-group">
            <div class="controls">
                <button type="reset" class="btn btn-default">清 空</button>
                <button type="submit" class="btn btn-success">提 交</button>
            </div>
        </div>
    </form>

@stop

@section('end')
    @parent
    {{ script('markdown', 'bootstrap-markdown') }}
@stop

app/views/admin/article/edit.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent 编辑{{ $resourceName }} @stop

@section('beforeStyle')
    @parent
    {{ style('bootstrap-markdown') }}
@stop

@section('style')
.nav-tabs>li.active>a
{
    background-color: #f8f8f8 !important;
}
@parent @stop

@section('container')

    @include('w.notification')
    <h3>
        编辑{{ $resourceName }}
        <div class="pull-right">
            <a href="{{ route($resource.'.index') }}" class="btn btn-sm btn-default">
                &laquo; 返回{{ $resourceName }}列表
            </a>
        </div>
    </h3>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-general" data-toggle="tab">主要内容</a></li>
        <li><a href="#tab-meta-data" data-toggle="tab">SEO</a></li>
        <li><a href="#tab-info" data-toggle="tab">文章相关信息</a></li>
    </ul>

    <form class="form-horizontal" method="post" action="{{ route($resource.'.update', $data->id) }}" autocomplete="off"
        style="background:#f8f8f8;padding:1em;border:1px solid #ddd;border-top:0;">
        <!-- CSRF Token -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />
        <input type="hidden" name="_method" value="PUT" />

        <!-- Tabs Content -->
        <div class="tab-content">

            <!-- General tab -->
            <div class="tab-pane active" id="tab-general" style="margin:0 1em;">

                <div class="form-group">
                    <label for="category">分类</label>
                    {{ $errors->first('category', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    {{ Form::select('category', $categoryLists, $data->category->id, array('class' => 'form-control')) }}
                </div>

                <div class="form-group">
                    <label for="title">标题</label>
                    {{ $errors->first('title', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="text" name="title" id="title" value="{{ Input::old('title', $data->title) }}" />
                </div>

                <div class="form-group">
                    <label for="slug">Slug</label>
                    {{ $errors->first('slug', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <div class="input-group">
                        <span class="input-group-addon" >
                            {{ str_finish(URL::to('/'), '/') }}
                        </span>
                        <input class="form-control" type="text" name="slug" id="slug" value="{{ Input::old('slug', $data->slug) }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="content">内容</label>
                    {{ $errors->first('content', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <textarea id="content" class="form-control" data-provide="markdown"
                        name="content" rows="10">{{ Input::old('content', $data->content_markdown) }}</textarea>
                </div>

            </div>

            <!-- Meta Data tab -->
            <div class="tab-pane" id="tab-meta-data" style="margin:0 1em;">

                <div class="form-group">
                    <label for="meta_title">Meta Title</label>
                    <input class="form-control" type="text" name="meta_title" id="meta_title" value="{{ Input::old('meta_title', $data->meta_title) }}" />
                </div>

                <div class="form-group">
                    <label for="meta_description">Meta Description</label>
                    <input class="form-control" type="text" name="meta_description" id="meta_description" value="{{ Input::old('meta_description', $data->meta_description) }}" />
                </div>

                <div class="form-group">
                    <label for="meta_keywords">Meta Keywords</label>
                    <input class="form-control" type="text" name="meta_keywords" id="meta_keywords" value="{{ Input::old('meta_keywords', $data->meta_keywords) }}" />
                </div>

            </div>

            <!-- Info tab -->
            <div class="tab-pane" id="tab-info" style="margin:0 1em 2em 1em;">

                <div class="form-group">
                    <label>作者</label>
                    <p class="form-control-static">{{ $data->user ? $data->user->email : '作者信息丢失' }}</p>
                </div>

                <div class="form-group">
                    <label>创建时间</label>
                    <p class="form-control-static">{{ $data->created_at }}（{{ $data->friendly_created_at }}）</p>
                </div>

                <div class="form-group">
                    <label>最后修改时间</label>
                    <p class="form-control-static">{{ $data->updated_at }}（{{ $data->friendly_updated_at }}）</p>
                </div>

            </div>


        </div>

        <!-- Form actions -->
        <div class="control-group">
            <div class="controls">
                <a class="btn btn-default" href="{{ route($resource.'.edit', $data->id) }}">重 置</a>
                <button type="submit" class="btn btn-success">提 交</button>
            </div>
        </div>
    </form>

@stop

@section('end')
    @parent
    {{ script('markdown', 'to-markdown', 'bootstrap-markdown') }}
@stop

app/views/admin/article/index.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent {{ $resourceName }}管理 @stop

@section('container')

    @include('w.notification')

    <h3>
        {{ $resourceName }}管理
        <div class="pull-right">
            <a href="{{ route($resource.'.create') }}" class="btn btn-sm btn-primary">
                添加新{{ $resourceName }}
            </a>
        </div>
    </h3>

    {{ Form::open(array('method' => 'get')) }}
        <div class="input-group col-md-9" style="margin:0 auto 1em auto;">
            <span class="input-group-btn" style="width:6em;">
                {{
                    Form::select(
                        'target',
                        array('title' => '标题'),
                        Input::get('target', 'title'),
                        array('class' => 'form-control input-sm')
                    )
                }}
            </span>
            <input type="text" class="form-control input-sm" name="like" placeholder="请输入搜索条件" value="{{ Input::get('like') }}">
            <span class="input-group-btn">
                <button class="btn btn-sm btn-default" type="submit" style="width:5em;">搜索</button>
            </span>
        </div>
    {{ Form::close() }}

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>标题 {{ order_by('title') }}</th>
                    <th>评论数 {{ order_by('comments_count') }}</th>
                    <th>创建时间 {{ order_by('created_at', 'desc') }}</th>
                    <th style="width:7em;text-align:center;">操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($datas as $data)
                <tr>
                    <td>
                        <a href="{{ route('blog.show', $data->slug) }}" target="_blank">
                            <i class="glyphicon glyphicon-share" style="font-size:0.5em;"></i>
                        </a>
                        {{ $data->title }}
                    </td>
                    <td>{{ $data->comments_count }}</td>
                    <td>{{ $data->created_at }}（{{ $data->friendly_created_at }}）</td>
                    <td>
                        <a href="{{ route($resource.'.edit', $data->id) }}" class="btn btn-xs">编辑</a>
                        <a href="javascript:void(0)" class="btn btn-xs btn-danger"
                             onclick="modal('{{ route($resource.'.destroy', $data->id) }}')">删除</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="pull-right" style="">
        {{ pagination($datas->appends(Input::except('page')), 'p.slider-3') }}
    </div>

<?php
$modalData['modal'] = array(
    'id'      => 'myModal',
    'title'   => '系统提示',
    'message' => '确认删除此'.$resourceName.'？',
    'footer'  =>
        Form::open(array('id' => 'real-delete', 'method' => 'delete')).'
            <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">取消</button>
            <button type="submit" class="btn btn-sm btn-danger">确认删除</button>'.
        Form::close(),
);
?>
    @include('w.modal', $modalData)

@stop

@section('end')
    @parent
    <script>
        function modal(href)
        {
            $('#real-delete').attr('action', href);
            $('#myModal').modal();
        }
    </script>
@stop