app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| 基础权限
|--------------------------------------------------------------------------
*/
RouteGroup::make('auth')->before('guest')->controller('AuthorityController')->go(function ($route) {

    # 退出
    $route->get('logout')->as('logout')->uses('getLogout')->beforeClear();

    # 登录
    $route->get( 'signin'                   )->as('signin'        )->uses('getSignin'         );
    $route->post('signin'                   )                      ->uses('postSignin'        );
    # 注册
    $route->get( 'signup'                   )->as('signup'        )->uses('getSignup'         );
    $route->post('signup'                   )                      ->uses('postSignup'        );
    # 注册成功提示用户激活
    $route->get( 'success/{email}'          )->as('signupSuccess' )->uses('getSignupSuccess'  );
    # 激活账号
    $route->get( 'activate/{activationCode}')->as('activate'      )->uses('getActivate'       );
    # 忘记密码
    $route->get( 'forgot-password'          )->as('forgotPassword')->uses('getForgotPassword' );
    $route->post('forgot-password'          )                      ->uses('postForgotPassword');
    # 密码重置
    $route->get( 'forgot-password/{token}'  )->as('reset'         )->uses('getReset'          );
    $route->post('forgot-password/{token}'  )                      ->uses('postReset'         );

});

/*
|--------------------------------------------------------------------------
| 管理员后台
|--------------------------------------------------------------------------
*/
Route::group(array('prefix' => 'admin', 'before' => 'auth|admin'), function () {

    # 后台首页
    RouteGroup::make()->controller('AdminController')->go(function ($route) {
        $route->get('/')->as('admin')->uses('getIndex');
    });

    # 用户管理
    RouteGroup::make('users')->as('users')->controller('Admin_UserResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )->before('not.self')
              ->update()->before('not.self');
        $route->delete('{id}')->as('destroy')->uses('destroy')->before('not.self');
    });

    # 文章分类管理
    RouteGroup::make('categories')->as('categories')->controller('Admin_CategoryResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

    # 文章管理
    RouteGroup::make('articles')->as('articles')->controller('Admin_ArticleResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

});


/*
|--------------------------------------------------------------------------
| 用户中心
|--------------------------------------------------------------------------
*/
RouteGroup::make('account')->as('account')->before('auth')->controller('AccountController')->go(function ($route) {

    # 用户中心首页
    $route->get(   '/'               )->as('index'             )->uses('getIndex'         );
    # 修改当前账号密码
    $route->get(   'change-password' )->as('changePassword'    )->uses('getChangePassword');
    $route->put(   'change-password' )                          ->uses('putChangePassword');
    # 更改头像
    $route->get(   'change-portrait' )->as('changePortrait'    )->uses('getChangePortrait');
    $route->put(   'change-portrait' )                          ->uses('putChangePortrait');
    # 我的评论管理
    $route->get(   'my-comments'     )->as('myComments'        )->uses('getMyComments'    );
    $route->delete('my-comments/{id}')->as('myComments.destroy')->uses('deleteMyComment'  );

});

/*
|--------------------------------------------------------------------------
| 博客
|--------------------------------------------------------------------------
*/
RouteGroup::make()->controller('BlogController')->go(function ($route) {

    # 博客首页
    $route->get( '/'            )->as('home'            )->uses('getIndex'           );
    # 分类文章列表
    $route->get( 'category/{id}')->as('categoryArticles')->uses('getCategoryArticles');
    # 展示博客文章
    $route->get( '{slug}'       )->as('blog.show'       )->uses('getBlogShow'        );
    # 提交文章评论
    $route->post('{slug}'       )                        ->uses('postBlogComment'    )->before('auth');

})/*->ddAll()*/;

/*
|--------------------------------------------------------------------------
| 特殊功能
|--------------------------------------------------------------------------
*/

app/models/BaseModel.php
<?php

class BaseModel extends Eloquent
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = false;

    /**
     * 自动维护时间戳
     * @var boolean
     */
    public $timestamps = true;

    /**
     * 其它需要使用日期调整器的字段
     * @var array
     */
    protected $dates = array();

    /**
     * 集体赋值白名单（高优先级）
     * @var array
     */
    protected $fillable = array();

    /**
     * 集体赋值黑名单
     * @var array
     */
    protected $guarded = array();

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 友好的创建时间
     * @return string
     */
    public function getFriendlyCreatedAtAttribute()
    {
        return friendly_date($this->created_at);
    }

    /**
     * 友好的更新时间
     * @return string
     */
    public function getFriendlyUpdatedAtAttribute()
    {
        return friendly_date($this->updated_at);
    }

    /**
     * 友好的删除时间
     * @return string
     */
    public function getFriendlyDeletedAtAttribute()
    {
        return friendly_date($this->deleted_at);
    }


}

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends BaseModel implements UserInterface, RemindableInterface
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = true;

/*
|--------------------------------------------------------------------------
| Auth 支持
|--------------------------------------------------------------------------
*/
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password');

    /**
     * Get the unique identifier for the user.
     *
     * @return mixed
     */
    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Get the password for the user.
     *
     * @return string
     */
    public function getAuthPassword()
    {
        return $this->password;
    }

    /**
     * Get the token value for the "remember me" session.
     *
     * @return string
     */
    public function getRememberToken()
    {
        return $this->remember_token;
    }

    /**
     * Set the token value for the "remember me" session.
     *
     * @param  string  $value
     * @return void
     */
    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    /**
     * Get the column name for the "remember me" token.
     *
     * @return string
     */
    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    /**
     * Get the e-mail address where password reminders are sent.
     *
     * @return string
     */
    public function getReminderEmail()
    {
        return $this->email;
    }

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 友好的最后登录时间
     * @return string
     */
    public function getFriendlySigninAtAttribute()
    {
        if (is_null($this->signin_at))
            return '新账号尚未登录';
        else
            return friendly_date($this->signin_at);
    }

    /**
     * 用户头像（大）
     * @return string 用户头像的 URI
     */
    public function getPortraitLargeAttribute()
    {
        if ($this->portrait)
            return asset('portrait/large/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 220);
    }

    /**
     * 用户头像（中）
     * @return string 用户头像的 URI
     */
    public function getPortraitMediumAttribute()
    {
        if ($this->portrait)
            return asset('portrait/medium/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 128);
    }

    /**
     * 用户头像（小）
     * @return string 用户头像的 URI
     */
    public function getPortraitSmallAttribute()
    {
        if ($this->portrait)
            return asset('portrait/small/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 64);
    }

/*
|--------------------------------------------------------------------------
| 调整器
|--------------------------------------------------------------------------
*/
    /**
     * 密码
     * @param  string $value 未处理的密码字符串
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        // 若传入的字符串已经进行了 Hash 加密，则不重复处理
        $this->attributes['password'] = Hash::needsRehash($value) ? Hash::make($value) : $value;
    }


}

app/views/admin/user/create.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent 添加新{{ $resourceName }} @stop

@section('beforeStyle')
    @parent
    {{ style('bootstrap-3-switch') }}
@stop

@section('style')
.nav-tabs>li.active>a
{
    background-color: #f8f8f8 !important;
}
@parent @stop

@section('container')

    @include('w.notification')
    <h3>
        添加新{{ $resourceName }}
        <div class="pull-right">
            <a href="{{ route($resource.'.index') }}" class="btn btn-sm btn-default">
                &laquo; 返回{{ $resourceName }}列表
            </a>
        </div>
    </h3>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-general" data-toggle="tab">主要内容</a></li>
        <li><a href="#tab-meta-data" data-toggle="tab">权限相关</a></li>
    </ul>

    <form class="form-horizontal" method="post" action="{{ route($resource.'.store') }}" autocomplete="off"
        style="background:#f8f8f8;padding:1em;border:1px solid #ddd;border-top:0;">
        <!-- CSRF Token -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />

        <!-- Tabs Content -->
        <div class="tab-content">

            <!-- General tab -->
            <div class="tab-pane active" id="tab-general" style="margin:0 1em;">
                
                <div class="form-group">
                    <label for="email">邮箱</label>
                    {{ $errors->first('email', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="text" name="email" id="email" value="{{ Input::old('email') }}" />
                </div>
                
                <div class="form-group">
                    <label for="password">密码</label>
                    {{ $errors->first('password', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="password" name="password" id="password" value="" />
                </div>
                
                <div class="form-group">
                    <label for="password_confirmation">确认密码</label>
                    <input class="form-control" type="password" name="password_confirmation" id="password_confirmation" value="" />
                </div>

            </div>

            <!-- Meta Data tab -->
            <div class="tab-pane" id="tab-meta-data" style="margin:0 1em;">
                
                <div class="form-group">
                    <label for="meta_title">用户身份</label>
                    {{ $errors->first('is_admin', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <div>
                        <input type="checkbox" name="is_admin" value="1"
                            {{ Input::old('is_admin') ? 'checked': ''; }}
                            data-on="danger" data-off="default" data-text-label="　　　　"
                            data-on-label="管理员" data-off-label="普通用户">
                    </div>
                </div>

            </div>

        </div>

        <!-- Form actions -->
        <div class="control-group">
            <div class="controls">
                <button type="reset" class="btn btn-default">清 空</button>
                <button type="submit" class="btn btn-success">提 交</button>
            </div>
        </div>
    </form>

@stop

@section('end')
    @parent
    {{ script('bootstrap-3-switch') }}
    <script>
         $('input[type="checkbox"],[type="radio"]').bootstrapSwitch();
    </script>
@stop

app/views/admin/user/edit.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent 编辑{{ $resourceName }} @stop

@section('beforeStyle')
    @parent
    {{ style('bootstrap-3-switch') }}
@stop

@section('style')
.nav-tabs>li.active>a
{
    background-color: #f8f8f8 !important;
}
@parent @stop

@section('container')

    @include('w.notification')
    <h3>
        编辑{{ $resourceName }}
        <div class="pull-right">
            <a href="{{ route($resource.'.index') }}" class="btn btn-sm btn-default">
                &laquo; 返回{{ $resourceName }}列表
            </a>
        </div>
    </h3>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-general" data-toggle="tab">主要内容</a></li>
        <li><a href="#tab-meta-data" data-toggle="tab">权限相关</a></li>
    </ul>

    <form class="form-horizontal" method="post" action="{{ route($resource.'.update', $data->id) }}" autocomplete="off"
        style="background:#f8f8f8;padding:1em;border:1px solid #ddd;border-top:0;">
        <!-- CSRF Token -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />
        <input type="hidden" name="_method" value="PUT" />

        <!-- Tabs Content -->
        <div class="tab-content">

            <!-- General tab -->
            <div class="tab-pane active" id="tab-general" style="margin:0 1em;">
                
                <div class="form-group">
                    <label for="email">邮箱</label>
                    {{ $errors->first('email', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="text" name="email" id="email" value="{{ Input::old('email', $data->email) }}" />
                </div>
                
                <div class="form-group">
                    <label for="password">密码</label>
                    {{ $errors->first('password', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <input class="form-control" type="password" name="password" id="password" value="" />
                </div>
                
                <div class="form-group">
                    <label for="password_confirmation">确认密码</label>
                    <input class="form-control" type="password" name="password_confirmation" id="password_confirmation" value="" />
                </div>

            </div>

            <!-- Meta Data tab -->
            <div class="tab-pane" id="tab-meta-data" style="margin:0 1em;">
                
                <div class="form-group">
                    <label for="meta_title">用户身份</label>
                    {{ $errors->first('is_admin', '<span style="color:#c7254e;margin:0 1em;">:message</span>') }}
                    <div>
                        <input type="checkbox" name="is_admin" value="1"
                            {{ Input::old('is_admin', $data->is_admin) ? 'checked': ''; }}
                            data-on="danger" data-off="default" data-text-label="　　　　"
                            data-on-label="管理员" data-off-label="普通用户">
                    </div>
                </div>

            </div>

        </div>

        <!-- Form actions -->
        <div class="control-group">
            <div class="controls">
                <a class="btn btn-default" href="{{ route($resource.'.edit', $data->id) }}">重 置</a>
                <button type="submit" class="btn btn-success">提 交</button>
            </div>
        </div>
    </form>

@stop

@section('end')
    @parent
    {{ script('bootstrap-3-switch') }}
    <script>
         $('input[type="checkbox"],[type="radio"]').bootstrapSwitch();
    </script>
@stop

app/views/admin/user/index.blade.php
@extends('l.admin', array('active' => $resource))

@section('title') @parent {{ $resourceName }}管理 @stop

@section('container')

    @include('w.notification')

    <h3>
        {{ $resourceName }}管理
        <div class="pull-right">
            <a href="{{ route($resource.'.create') }}" class="btn btn-sm btn-primary">
                添加新{{ $resourceName }}
            </a>
        </div>
    </h3>

    {{ Form::open(array('method' => 'get')) }}
        <div class="input-group col-md-9" style="margin:0 auto 1em auto;">
            <span class="input-group-btn" style="width:8em;">
                {{
                    Form::select(
                        'status',
                        array('all' => '所有', '1' => '管理员', '0' => '普通用户'),
                        Input::get('status', 'all'),
                        array('class' => 'form-control input-sm')
                    )
                }}
            </span>
            <span class="input-group-btn" style="width:6em;">
                {{
                    Form::select(
                        'target',
                        array('email' => '邮箱'),
                        Input::get('target', 'email'),
                        array('class' => 'form-control input-sm')
                    )
                }}
            </span>
            <input type="text" class="form-control input-sm" name="like" placeholder="请输入搜索条件" value="{{ Input::get('like') }}">
            <span class="input-group-btn">
                <button class="btn btn-sm btn-default" type="submit" style="width:5em;">搜索</button>
            </span>
        </div>
    {{ Form::close() }}

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>身份 {{ order_by('is_admin') }}</th>
                    <th>邮箱 {{ order_by('email') }}</th>
                    <th>注册时间 {{ order_by('created_at', 'desc') }}</th>
                    <th>最后登录时间 {{ order_by('signin_at') }}</th>
                    <th style="width:7em;text-align:center;">操作</th>
                </tr>
            </thead>
            <tbody>
                <?php $currentId = Auth::user()->id; ?>
                @foreach ($datas as $data)
                <tr>
                    <td>{{ $data->is_admin ? '管理员' : '普通用户' }}</td>
                    <td>{{ $data->email }}</td>
                    <td>{{ $data->created_at }}（{{ $data->friendly_created_at }}）</td>
                    <td>{{ $data->signin_at }}（{{ $data->friendly_signin_at }}）</td>
                    <td>
                        @if($data->id!=$currentId)
                        <a href="{{ route($resource.'.edit', $data->id) }}" class="btn btn-xs">编辑</a>
                        <a href="javascript:void(0)" class="btn btn-xs btn-danger"
                             onclick="modal('{{ route($resource.'.destroy', $data->id) }}')">删除</a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="pull-right" style="">
        {{ pagination($datas->appends(Input::except('page')), 'p.slider-3') }}
    </div>

<?php
$modalData['modal'] = array(
    'id'      => 'myModal',
    'title'   => '系统提示',
    'message' => '确认删除此'.$resourceName.'？',
    'footer'  =>
        Form::open(array('id' => 'real-delete', 'method' => 'delete')).'
            <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">取消</button>
            <button type="submit" class="btn btn-sm btn-danger">确认删除</button>'.
        Form::close(),
);
?>
    @include('w.modal', $modalData)

@stop

@section('end')
    @parent
    <script>
        function modal(href)
        {
            $('#real-delete').attr('action', href);
            $('#myModal').modal();
        }
    </script>
@stop