app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| 基础权限
|--------------------------------------------------------------------------
*/
RouteGroup::make('auth')->before('guest')->controller('AuthorityController')->go(function ($route) {

    # 退出
    $route->get('logout')->as('logout')->uses('getLogout')->beforeClear();

    # 登录
    $route->get( 'signin'                   )->as('signin'        )->uses('getSignin'         );
    $route->post('signin'                   )                      ->uses('postSignin'        );
    # 注册
    $route->get( 'signup'                   )->as('signup'        )->uses('getSignup'         );
    $route->post('signup'                   )                      ->uses('postSignup'        );
    # 注册成功提示用户激活
    $route->get( 'success/{email}'          )->as('signupSuccess' )->uses('getSignupSuccess'  );
    # 激活账号
    $route->get( 'activate/{activationCode}')->as('activate'      )->uses('getActivate'       );
    # 忘记密码
    $route->get( 'forgot-password'          )->as('forgotPassword')->uses('getForgotPassword' );
    $route->post('forgot-password'          )                      ->uses('postForgotPassword');
    # 密码重置
    $route->get( 'forgot-password/{token}'  )->as('reset'         )->uses('getReset'          );
    $route->post('forgot-password/{token}'  )                      ->uses('postReset'         );

});

/*
|--------------------------------------------------------------------------
| 管理员后台
|--------------------------------------------------------------------------
*/
Route::group(array('prefix' => 'admin', 'before' => 'auth|admin'), function () {

    # 后台首页
    RouteGroup::make()->controller('AdminController')->go(function ($route) {
        $route->get('/')->as('admin')->uses('getIndex');
    });

    # 用户管理
    RouteGroup::make('users')->as('users')->controller('Admin_UserResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )->before('not.self')
              ->update()->before('not.self');
        $route->delete('{id}')->as('destroy')->uses('destroy')->before('not.self');
    });

    # 文章分类管理
    RouteGroup::make('categories')->as('categories')->controller('Admin_CategoryResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

    # 文章管理
    RouteGroup::make('articles')->as('articles')->controller('Admin_ArticleResource')->go(function ($route) {
        $route->index( )
              ->create()
              ->store( )
              ->edit(  )
              ->update();
        $route->delete('{id}')->as('destroy')->uses('destroy');
    });

});


/*
|--------------------------------------------------------------------------
| 用户中心
|--------------------------------------------------------------------------
*/
RouteGroup::make('account')->as('account')->before('auth')->controller('AccountController')->go(function ($route) {

    # 用户中心首页
    $route->get(   '/'               )->as('index'             )->uses('getIndex'         );
    # 修改当前账号密码
    $route->get(   'change-password' )->as('changePassword'    )->uses('getChangePassword');
    $route->put(   'change-password' )                          ->uses('putChangePassword');
    # 更改头像
    $route->get(   'change-portrait' )->as('changePortrait'    )->uses('getChangePortrait');
    $route->put(   'change-portrait' )                          ->uses('putChangePortrait');
    # 我的评论管理
    $route->get(   'my-comments'     )->as('myComments'        )->uses('getMyComments'    );
    $route->delete('my-comments/{id}')->as('myComments.destroy')->uses('deleteMyComment'  );

});

/*
|--------------------------------------------------------------------------
| 博客
|--------------------------------------------------------------------------
*/
RouteGroup::make()->controller('BlogController')->go(function ($route) {

    # 博客首页
    $route->get( '/'            )->as('home'            )->uses('getIndex'           );
    # 分类文章列表
    $route->get( 'category/{id}')->as('categoryArticles')->uses('getCategoryArticles');
    # 展示博客文章
    $route->get( '{slug}'       )->as('blog.show'       )->uses('getBlogShow'        );
    # 提交文章评论
    $route->post('{slug}'       )                        ->uses('postBlogComment'    )->before('auth');

})/*->ddAll()*/;

/*
|--------------------------------------------------------------------------
| 特殊功能
|--------------------------------------------------------------------------
*/

app/models/Article.php
<?php

use \Michelf\MarkdownExtra;

/**
 * 文章
 */
class Article extends BaseModel
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = true;

/*
|--------------------------------------------------------------------------
| 模型对象关系
|--------------------------------------------------------------------------
*/
    /**
     * 文章的分类
     * 一对多逆向
     * @return object Category
     */
    public function category()
    {
        return $this->belongsTo('Category', 'category_id');
    }

    /**
     * 文章的作者
     * 一对多逆向
     * @return object User
     */
    public function user()
    {
        return $this->belongsTo('User', 'user_id');
    }

    /**
     * 文章的评论
     * 一对多
     * @return object Illuminate\Database\Eloquent\Collection
     */
    public function comments()
    {
        return $this->hasMany('Comment', 'article_id');
    }

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 文章内容（原始）
     * @return string
     */
    public function getContentAttribute($value)
    {
        return strip($value);
    }

    /**
     * 文章内容（HTML 格式）
     * @return string
     */
    public function getContentHtmlAttribute()
    {
        switch ($this->content_format) {
            case 'markdown':
                return MarkdownExtra::defaultTransform($this->content);
            case 'html':
                return $this->content;
        }
    }

    /**
     * 文章内容（Markdown 格式）
     * @return string
     */
    public function getContentMarkdownAttribute()
    {
        switch ($this->content_format) {
            case 'markdown':
                return $this->content;
            case 'html':
                return new HTML_To_Markdown($this->content);
        }
    }


}

app/models/BaseModel.php
<?php

class BaseModel extends Eloquent
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = false;

    /**
     * 自动维护时间戳
     * @var boolean
     */
    public $timestamps = true;

    /**
     * 其它需要使用日期调整器的字段
     * @var array
     */
    protected $dates = array();

    /**
     * 集体赋值白名单（高优先级）
     * @var array
     */
    protected $fillable = array();

    /**
     * 集体赋值黑名单
     * @var array
     */
    protected $guarded = array();

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 友好的创建时间
     * @return string
     */
    public function getFriendlyCreatedAtAttribute()
    {
        return friendly_date($this->created_at);
    }

    /**
     * 友好的更新时间
     * @return string
     */
    public function getFriendlyUpdatedAtAttribute()
    {
        return friendly_date($this->updated_at);
    }

    /**
     * 友好的删除时间
     * @return string
     */
    public function getFriendlyDeletedAtAttribute()
    {
        return friendly_date($this->deleted_at);
    }


}

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends BaseModel implements UserInterface, RemindableInterface
{
    /**
     * 软删除
     * @var boolean
     */
    protected $softDelete = true;

/*
|--------------------------------------------------------------------------
| Auth 支持
|--------------------------------------------------------------------------
*/
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password');

    /**
     * Get the unique identifier for the user.
     *
     * @return mixed
     */
    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Get the password for the user.
     *
     * @return string
     */
    public function getAuthPassword()
    {
        return $this->password;
    }

    /**
     * Get the token value for the "remember me" session.
     *
     * @return string
     */
    public function getRememberToken()
    {
        return $this->remember_token;
    }

    /**
     * Set the token value for the "remember me" session.
     *
     * @param  string  $value
     * @return void
     */
    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    /**
     * Get the column name for the "remember me" token.
     *
     * @return string
     */
    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    /**
     * Get the e-mail address where password reminders are sent.
     *
     * @return string
     */
    public function getReminderEmail()
    {
        return $this->email;
    }

/*
|--------------------------------------------------------------------------
| 访问器
|--------------------------------------------------------------------------
*/
    /**
     * 友好的最后登录时间
     * @return string
     */
    public function getFriendlySigninAtAttribute()
    {
        if (is_null($this->signin_at))
            return '新账号尚未登录';
        else
            return friendly_date($this->signin_at);
    }

    /**
     * 用户头像（大）
     * @return string 用户头像的 URI
     */
    public function getPortraitLargeAttribute()
    {
        if ($this->portrait)
            return asset('portrait/large/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 220);
    }

    /**
     * 用户头像（中）
     * @return string 用户头像的 URI
     */
    public function getPortraitMediumAttribute()
    {
        if ($this->portrait)
            return asset('portrait/medium/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 128);
    }

    /**
     * 用户头像（小）
     * @return string 用户头像的 URI
     */
    public function getPortraitSmallAttribute()
    {
        if ($this->portrait)
            return asset('portrait/small/'.$this->portrait);
        else
            return with(new Identicon)->getImageDataUri($this->email, 64);
    }

/*
|--------------------------------------------------------------------------
| 调整器
|--------------------------------------------------------------------------
*/
    /**
     * 密码
     * @param  string $value 未处理的密码字符串
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        // 若传入的字符串已经进行了 Hash 加密，则不重复处理
        $this->attributes['password'] = Hash::needsRehash($value) ? Hash::make($value) : $value;
    }


}

app/controllers/BlogController.php
<?php

class BlogController extends BaseController
{
    /**
     * 博客首页
     * @return Respanse
     */
    public function getIndex()
    {
        $articles   = Article::orderBy('created_at', 'desc')->paginate(5);
        $categories = Category::orderBy('sort_order')->get();
        return View::make('blog.index')->with(compact('articles', 'categories'));
    }

    /**
     * 分类文章列表
     * @return Respanse
     */
    public function getCategoryArticles($category_id)
    {
        $articles   = Article::where('category_id', $category_id)->orderBy('created_at', 'desc')->paginate(5);
        $categories = Category::orderBy('sort_order')->get();
        return View::make('blog.categoryArticles')->with(compact('articles', 'categories', 'category_id'));
    }

    /**
     * 博客文章展示页面
     * @param  string $slug 文章缩略名
     * @return response
     */
    public function getBlogShow($slug)
    {
        $article    = Article::where('slug', $slug)->first();
        is_null($article) AND App::abort(404);
        $categories = Category::orderBy('sort_order')->get();
        return View::make('blog.show')->with(compact('article', 'categories'));
    }

    /**
     * 提交评论
     * @param  string $slug 文章缩略名
     * @return response
     */
    public function postBlogComment($slug)
    {
        // 获取评论内容
        $content = e(Input::get('content'));
        // 字数检查
        if (mb_strlen($content)<3)
            return Redirect::back()->withInput()->withErrors($this->messages->add('content', '评论不得少于3个字符。'));
        // 查找对应文章
        $article = Article::where('slug', $slug)->first();
        // 创建文章评论
        $comment = new Comment;
        $comment->content    = $content;
        $comment->article_id = $article->id;
        $comment->user_id    = Auth::user()->id;
        if ($comment->save()) {
            // 创建成功
            // 更新评论数
            $article->comments_count = $article->comments->count();
            $article->save();
            // 返回成功信息
            return Redirect::back()->with('success', '评论成功。');
        } else {
            // 创建失败
            return Redirect::back()->withInput()->with('error', '评论失败。');
        }
    }

}

app/views/blog/categoryArticles.blade.php
@extends('l.blog', array('active' => 'home'))

@section('container')

    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <div class="row">

                @foreach($articles as $article)
                <div class="col-6 col-sm-6 col-lg-12 panel">
                    <h2>
                        <a href="{{ route('blog.show', $article->slug) }}">{{ $article->title }}</a>
                        <a target="_blank" class="pull-left" 
                            href="{{ route('blog.show', $article->slug) }}">
                            <i class="glyphicon glyphicon-share" style="font-size:0.5em;margin-right:1em;"></i>
                        </a>
                    </h2>
                    <p>{{ close_tags(Str::limit($article->content_html, 200)) }}</p>
                    <p>
                        <i class="glyphicon glyphicon-calendar"></i><span> {{ $article->created_at }}（{{ $article->friendly_created_at }}）</span>
                        <a target="_blank" href="{{ route('blog.show', $article->slug) }}#comments">
                            <i class="glyphicon glyphicon-share" style="font-size:0.5em;"></i>
                        </a>
                        <a href="{{ route('blog.show', $article->slug) }}#comments"
                            class="btn btn-default btn-xs" style="margin-top:-2px;"
                            role="button">评论（{{ $article->comments_count }}）</a>
                    </p>
                </div><!--/span-->
                @endforeach

                <div>
                    {{ pagination($articles, 'p.slider-3') }}
                </div>

            </div><!--/row-->
        </div><!--/span-->

        @include('w.blogSidebar', array('activeCategory' => $category_id))
        
    </div><!--/row-->

@stop

app/views/blog/index.blade.php
@extends('l.blog', array('active' => 'home'))

@section('container')

    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <div class="row">

                @foreach($articles as $article)
                <div class="col-6 col-sm-6 col-lg-12 panel">
                    <h2>
                        <a href="{{ route('blog.show', $article->slug) }}">{{ $article->title }}</a>
                        <a target="_blank" class="pull-left" 
                            href="{{ route('blog.show', $article->slug) }}">
                            <i class="glyphicon glyphicon-share" style="font-size:0.5em;margin-right:1em;"></i>
                        </a>
                    </h2>
                    <p>{{ close_tags(Str::limit($article->content_html, 200)) }}</p>
                    <p>
                        <i class="glyphicon glyphicon-calendar"></i><span> {{ $article->created_at }}（{{ $article->friendly_created_at }}）</span>
                        <a target="_blank" href="{{ route('blog.show', $article->slug) }}#comments">
                            <i class="glyphicon glyphicon-share" style="font-size:0.5em;"></i>
                        </a>
                        <a href="{{ route('blog.show', $article->slug) }}#comments"
                            class="btn btn-default btn-xs" style="margin-top:-2px;"
                            role="button">评论（{{ $article->comments_count }}）</a>
                    </p>
                </div><!--/span-->
                @endforeach

                <div>
                    {{ pagination($articles, 'p.slider-3') }}
                </div>

            </div><!--/row-->
        </div><!--/span-->

        @include('w.blogSidebar', array('activeCategory' => 'all'))
        
    </div><!--/row-->

@stop

app/views/blog/show.blade.php
@extends('l.blog', array('active' => 'home'))

@section('description'){{ $article->description }} @stop
@section('keywords'){{ $article->keywords }} @stop
@section('title'){{ $article->title }} - @parent @stop

@section('container')

    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
        
            <div class="row">

                <div class="col-6 col-sm-6 col-lg-12 panel">
                    <h2>{{ $article->title }}</h2>
                    <hr />
                    <p>{{ $article->content_html }}</p>
                    <a name="comments"></a>
                    <p>
                        <i class="glyphicon glyphicon-calendar"></i><span> {{ $article->created_at }}（{{ $article->friendly_created_at }}）</span>
                    </p>
                </div><!--/span-->

                <div class="col-6 col-sm-6 col-lg-12 panel">
                    <h4>评论 - {{ $article->comments_count }}</h4>
                    <ul class="media-list">
                        <?php $article->load('comments.user') ?>
                        @foreach($article->comments as $comment)
                        <li class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-thumbnail" width="64" height="64" src="{{ $comment->user->portrait_small }}" alt="头像（小）">
                            </a>
                            <div class="media-body well well-sm">
                                <h5 class="media-heading">{{ $comment->user->email }}
                                    <small class="pull-right">发表于：{{ $comment->friendly_created_at }}</small>
                                </h5>
                                {{ $comment->content }}
                            </div>
                        </li>
                        @endforeach
                    </ul>
                    @include('w.notification')
                    @if(Auth::check())
                    <form class="form-horizontal" method="post" autocomplete="off">
                        <!-- CSRF Token -->
                        <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                        <textarea name="content" class="form-control" rows="3">{{ Input::old('content') }}</textarea>
                        {{ $errors->first('content', '<span style="color:#c7254e;margin-top:1em;">:message</span>') }}
                        <button type="submit" class="btn btn-success pull-right" style="margin:1em 0;">发表评论</button>
                    </form>
                    @else
                    <div class="form-horizontal">
                        <div class="form-control" style="height:5em">
                            <a class="btn btn-primary" href="{{ route('signin') }}">登录</a>
                            <a class="btn btn-success" href="{{ route('signup') }}">注册</a>
                        </div>
                        <button class="btn btn-defaut pull-right" style="margin:1em 0;">发表评论</button>
                    </div>
                    @endif
                </div><!--/span-->

            </div><!--/row-->
        </div><!--/span-->

        @include('w.blogSidebar', array('activeCategory' => $article->category->id))
        
    </div><!--/row-->

@stop